config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (MessageDetailView, MessageListView, MessageCreateView, MessageUpdateView,
                           MessageDeleteView, CustomersCreateView, CustomersUpdateView, CustomersDetailView,
                           CustomersListView, CustomersDeleteView)

app_name = MailingConfig.name

urlpatterns = [
    path('create_mailing/', MessageCreateView.as_view(), name='create'),
    path('create_custom/', CustomersCreateView.as_view(), name='create_custom'),
    path('edit_custom/<int:pk>/', CustomersUpdateView.as_view(), name='edit_custom'),
    path('customers/<int:pk>/', CustomersDetailView.as_view(), name='customers_detail'),
    path('delete_custom/<int:pk>/', CustomersDeleteView.as_view(), name='delete_custom'),
    path('customers_list/', CustomersListView.as_view(), name='customers_list'),
    path('', MessageListView.as_view(), name='home'),
    path('edit/<int:pk>/', MessageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='delete'),
    path('mailing/<int:pk>/', cache_page(120)(MessageDetailView.as_view()), name='mailing_detail'),
    ]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView, UsersDetail, block_user, UsersView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('manage/users/', UsersView.as_view(), name='manager_users'),
    path('manage/users/view/<int:pk>', UsersDetail.as_view(), name='manager_users_detail'),
    path('manage/users/block/<int:pk>', block_user, name='manager_users_block'),
]

mailing/models.py
from django.db import models
from django.utils import timezone
from users.models import User

class Customers(models.Model):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    fio = models.CharField(max_length=50, verbose_name='ФИО')
    comment = models.TextField(blank=True, verbose_name='Коммент')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True, blank=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def str(self):
        return f'{self.fio}: {self.email} - {self.comment}'


class Message(models.Model):
    subject_message = models.CharField(max_length=80, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Текст письма')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True, blank=True)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        permissions = [
            ('view_mailing', 'Может просматривать любые рассылки.')]

    def str(self):
        return f'{self.subject_message} - {self.message}'


class Mailing(models.Model):
    period_variants = (
        ('per_day', 'раз в день'),
        ('per_week', 'раз в неделю'),
        ('per_month', 'раз в месяц')
    )

    status_variants = (
        ('created', 'создана'),
        ('executing', 'запущена'),
        ('finished', 'закончена успешно'),
        ('error', 'законечена с ошибками')
    )

    start_time = models.DateTimeField(default=timezone.now, verbose_name='Начало рассылки')
    end_time = models.DateTimeField(null=True, blank=True, verbose_name='Конец рассылки')
    next_day = models.DateTimeField(null=True, blank=True, verbose_name='Следующая отправка рассылки')
    frequency = models.CharField(max_length=50, choices=period_variants, default='per_day',
                                 verbose_name='периодичность')
    mailing_status = models.CharField(max_length=80, choices=status_variants, default='created',
                                      verbose_name='статус рассылки')
    message = models.ForeignKey(Message, verbose_name='Cообщение', on_delete=models.CASCADE, blank=True, null=True)
    clients = models.ManyToManyField(Customers, related_name='mailing', verbose_name='Клиенты для рассылки')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Блокировка Рассылки')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def str(self):
        return f'{self.start_time} - {self.end_time} - {self.frequency} - {self.mailing_status}'


class Mailing_attempt(models.Model):
    status_variants = (
        ('successfully', 'успешно'),
        ('not_successful', 'не успешно'),
    )

    last_attempt = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.CharField(choices=status_variants, default=None, verbose_name='статус попытки')
    mail_response = models.CharField(max_length=50, verbose_name='ответ почтового сервера', blank=True, null=True)

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылок'
        permissions = [
            ('change_is_active', 'Может отключать рассылки.'), ]

    def str(self):
        return f'{self.last_attempt} - {self.status} - {self.mail_response}'

mailing/forms.py
from django import forms
from django.forms import BooleanField

from mailing.models import Mailing, Message, Customers

words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')


class StyleFormMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
                field.widget.attrs['placeholder'] = field.label
            else:
                field.widget.attrs['class'] = 'form-control'
                field.widget.attrs['placeholder'] = field.label


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('frequency', 'clients',)

    def clean_message(self):
        cleaned_data = self.cleaned_data.get('message', )

        if cleaned_data in words:
            raise forms.ValidationError('Возникла ошибка сообщении')
        return cleaned_data


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)

    def clean_message(self):
        cleaned_data = self.cleaned_data.get('message', )

        if cleaned_data in words:
            raise forms.ValidationError('Возникла ошибка сообщении')
        return cleaned_data


class MailingManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_active',)


class CustomersForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customers
        exclude = ('owner',)

    def clean_comment(self):
        cleaned_data = self.cleaned_data.get('comment', )

        if cleaned_data in words:
            raise forms.ValidationError('Возникла ошибка в описании ')
        return cleaned_data

    def clean_fio(self):
        cleaned_data = self.cleaned_data.get('fio', )

        if cleaned_data in words:
            raise forms.ValidationError('Возникла ошибка в ФИО')
        return cleaned_data

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from mailing.forms import MailingForm, MessageForm, CustomersForm, MailingManagerForm
from mailing.models import Mailing, Customers, Message, Mailing_attempt
from mailing.services import get_qs_from_cache


class MessageListView(ListView):
    model = Message
    template_name = 'mailing/home.html'


    def get_queryset(self):
       return get_qs_from_cache(qs=Message.objects.filter()[:20], key='message_list')

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(MessageListView, self).get_context_data(**kwargs)
        # Добавляем новую переменную к контексту и инициализируем её некоторым значением
        context['is_active'] = Mailing.objects.filter(is_active=True)
        context['customer'] = Customers.objects.all()
        context['message'] = Message.objects.all()

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        self.object = form.save()
        user = self.request.user
        self.object.owner = user
        self.object.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            return self.form_invalid(form)
        return super().form_valid(form)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MailingFormset = inlineformset_factory(Message, Mailing, form=MailingForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        mailing_template = form.save()
        self.object = form.save()
        self.object.owner = self.request.user
        mailing_template.owner = self.object.owner
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            mailing_template.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        user = self.request.user
        if user == self.object.owner:
            MailingFormset = inlineformset_factory(Message, Mailing, form=MailingForm, extra=1)
        elif user.is_staff or user.superuser:
            MailingFormset = inlineformset_factory(Message, Mailing, form=MailingManagerForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = MailingFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MailingFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        massage_template = form.save()
        self.object = form.save()
        self.object.owner = self.request.user
        massage_template.owner = self.object.owner
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            massage_template.save()
        return super().form_valid(form)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


def settings_toggle_active(request, pk):
    mailing_item = get_object_or_404(Mailing_attempt, pk=pk)
    if mailing_item.is_active is True:
        mailing_item.is_active = False
    else:
        mailing_item.is_active = True
        mailing_item.save()
    return redirect(reverse('mailing:home'))


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    template_name = 'mailing/message_detail.html'
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class CustomersCreateView(LoginRequiredMixin, CreateView):
    model = Customers
    form_class = CustomersForm
    success_url = reverse_lazy('mailing:home')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        customer = form.save()
        user = self.request.user
        customer.owner = user
        customer.save()
        return super().form_valid(form)


class CustomersUpdateView(LoginRequiredMixin, UpdateView):
    model = Customers
    form_class = CustomersForm
    success_url = reverse_lazy('mailing:customers_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        customer = form.save()
        user = self.request.user
        customer.owner = user
        customer.save()
        return super().form_valid(form)


class CustomersDeleteView(LoginRequiredMixin, DeleteView):
    model = Customers
    success_url = reverse_lazy('mailing:customers_list')
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class CustomersDetailView(DetailView):
    model = Customers
    template_name = 'mailing/customers_detail.html'
    login_url = "users:login"
    redirect_field_name = "redirect_to"


class CustomersListView(ListView):
    model = Customers
    template_name = 'mailing/customers_list.html'

    def get_queryset(self):
        return get_qs_from_cache(qs=Customers.objects.all(), key='customers_list')

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        self.object = form.save()
        user = self.request.user
        self.object.owner = user
        self.object.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            return self.form_invalid(form)
        return super().form_valid(form)

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Рассылка</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<header data-bs-theme = 'blue'>
 {% include 'mailing/includes/inc_menu.html' %}
</header>


{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Рассылка
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

mailing/templates/mailing/customers_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите удалить клиента "{{ object.fio }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'mailing:home'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/customers_detail.html
{% extends 'mailing/home.html' %}
{% load static %}

{% block content %}
    {% if user.is_block %}
        <div class="col-12 text-center">
            <h1>
                Ваш аккаунт заблокирован!
            </h1>
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-primary" type="submit">Выйти</button>
            </form>
        </div>
    {% else %}
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <p class="card-text">Почта: {{ object.email }}</p>
                                <p class="card-text">ФИO: {{ object.fio }}</p>
                                <p class="card-text">Комментарий: {{ object.comment|slice:100 }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

mailing/templates/mailing/customers_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="POST" enctype="multipart/form-data">

            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
      

        </form>
    </div>
{% endblock %}

mailing/templates/mailing/customers_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_block %}
        <div class="col-12 text-center">
            <h1>
                Ваш аккаунт заблокирован!
            </h1>
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-primary" type="submit">Выйти</button>
            </form>
        </div>
    {% else %}    
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылка</h1>
    <p class="lead">Рассылка - это отличный вариант для уведомления ваших пользователей</p>
     <p class="lead">Клиентов в нашем сервисе: {{ customers_list.count }}</p>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'mailing:create_custom'%}" role="button">Добавить клиента</a>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in customers_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Пользователь: {{ object.fio }}</p>
                        <p class="card-text">Почта: {{ object.email }}</p>
                        <p class="card-text">Описание: {{ object.comment }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'mailing:customers_detail' object.pk %}"
                                   role="button">Подробнее о клиентах</a>
                                {% if user.is_staff or user.superuser or user == object.owner %}
                                <a class="btn btn-warning" href="{% url 'mailing:edit_custom' object.pk %}"
                                   role="button">Редактировать</a>
                                {% endif %}
                                {% if user == object.owner %}
                                <a class="btn btn-danger" href="{% url 'mailing:delete_custom' object.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    {% endif %}
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
    {% if user.is_block %}
        <div class="col-12 text-center">
            <h1>
                Ваш аккаунт заблокирован!
            </h1>
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-primary" type="submit">Выйти</button>
            </form>
        </div>
    {% else %}
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Рассылка</h1>
            <p class="lead">Рассылка - это отличный вариант для уведомления ваших пользователей</p>
            <p class="lead">Создано рассылок в нашем сервисе: {{ message.count }}</p>
            <p class="lead">Активных рассылок в нашем сервисе: {{ is_active.count }}</p>
            <p class="lead">Клиентов в нашем сервисе: {{ customer.count }}</p>
            
            
        </div>
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="col-12 mb-5">
                    <a class="btn btn-primary" href="{% url 'mailing:create' %}" role="button">Создать Рассылку</a>
                    {% if user.is_staff or user.superuser %}
                        <a class="btn btn-primary" href="{% url 'mailing:customers_list' %}" role="button">Подробнее о
                            клиентах</a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'mailing:create_custom'%}" role="button">Добавить клиента</a>
                    {% endif %}
                </div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for object in message_list %}
                        {% if user.is_staff or user.superuser or user == object.owner %}
                            <div class="col">
                                <div class="card shadow-sm">
                                    <div class="card-body">
                                        <h5 class="card-text">{{ object.message }}</h5>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group">
                                                <a class="btn btn-primary"
                                                   href="{% url 'mailing:mailing_detail' object.pk %}"
                                                   role="button">Подробнее о рассылке</a>
                                                {% if user.is_staff or user == object.owner %}
                                                    <a class="btn btn-warning" href="{% url 'mailing:edit' object.pk %}"
                                                       role="button">Редактировать</a>
                                                {% endif %}
                                                {% if  user == object.owner %}
                                                    <a class="btn btn-danger"
                                                       href="{% url 'mailing:delete' object.pk %}"
                                                       role="button">Удалить</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку "{{ object.id }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'mailing:home'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

    {% if user.is_block %}
        <div class="col-12 text-center">
            <h1>
                Ваш аккаунт заблокирован!
            </h1>
           <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-primary" type="submit">Выйти</button>
            </form>
        </div>
    {% else %}
    
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p class="card-text">Тема письма: {{ message.subject_message }}</p>
                            <p class="card-text">Сообщение: {{ message.message }}</p>
                            <p class="card-text">Создано: {{ message.owner }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="POST" enctype="multipart/form-data">

            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}