config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import (MessageDetailView, MessageListView, MessageCreateView, MessageUpdateView,
                           MessageDeleteView, CustomersCreateView, CustomersUpdateView, CustomersDetailView,
                           CustomersListView, CustomersDeleteView)

app_name = MailingConfig.name

urlpatterns = [
    path('create_mailing/', MessageCreateView.as_view(), name='create'),
    path('create_custom/', CustomersCreateView.as_view(), name='create_custom'),
    path('edit_custom/<int:pk>/', CustomersUpdateView.as_view(), name='edit_custom'),
    path('customers/<int:pk>/', CustomersDetailView.as_view(), name='customers_detail'),
    path('delete_custom/<int:pk>/', CustomersDeleteView.as_view(), name='delete_custom'),
    path('customers_list/', CustomersListView.as_view(), name='customers_list'),
    path('', MessageListView.as_view(), name='home'),
    path('edit/<int:pk>/', MessageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='delete'),
    path('mailing/<int:pk>/', cache_page(120)(MessageDetailView.as_view()), name='mailing_detail'),
    ]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView, UsersDetail, block_user, UsersView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password'),
    path('manage/users/', UsersView.as_view(), name='manager_users'),
    path('manage/users/view/<int:pk>', UsersDetail.as_view(), name='manager_users_detail'),
    path('manage/users/block/<int:pk>', block_user, name='manager_users_block'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')

    first_name = models.CharField(max_length=150, verbose_name='Имя')

    last_name = models.CharField(max_length=150, verbose_name='Фамилия')

    avatar = models.ImageField(upload_to='users/photo', verbose_name='Аватар', blank=True, null=True,
                               help_text='Загрузите свой аватар')
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', blank=True,
                             null=True, help_text='Введите номер телефона')
    country = models.CharField(max_length=35, verbose_name='Страна', blank=True,
                               null=True, help_text='Введите страну')
    token = models.CharField(max_length=100, verbose_name='Токен', blank=True, null=True, )

    is_block = models.BooleanField(default=False, verbose_name='Блокировка пользователя')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            ('view_users', 'Может просматривать список пользователей сервиса.'),
            ('change_is_block', 'Может блокировать пользователей сервиса.')
        ]

    def __str__(self):
        return f'{self.email}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'avatar', 'country', 'phone')

users/views.py
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView

from config.settings import EMAIL_HOST_USER
from mailing.services import get_qs_from_cache
from users.forms import UserRegisterForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(20)
        user.token = token
        user.save(update_fields=['token', 'is_active'])
        host = self.request.get_host()
        url = f'https://{host}/users/email_confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Подтвердите вашу регистрацию перейдя по ссылке {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_confirm(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class GeneratePasswordView(PasswordResetView):
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            if user:
                password = User.objects.make_random_password(length=8)
                user.set_password(password)
                user.save(update_fields=['password'])
                send_mail(
                    'Смена пароля',
                    f'Ваш новый пароль: {password}',
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email],
                )
            return redirect(reverse("users:login"))


class UsersView(ListView):
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'objects_list'

    def get_queryset(self):
        return get_qs_from_cache(qs=User.objects.all(), key='users_list')


class UsersDetail(DetailView):
    model = User
    template_name = 'users/user_detail.html'
    context_object_name = 'objects_list'


def block_user(request, pk):
    user_item = get_object_or_404(User, pk=pk)
    if request.user.is_staff and user_item.is_superuser:
        rendered = render_to_string('users/403_forbiden.html')
        return HttpResponse(rendered, status=403)
    if user_item.is_block:
        user_item.is_block = False
    else:
        user_item.is_block = True
    user_item.save()
    return redirect(reverse('users:manager_users'))

users/templates/users/403_forbiden.html
{% extends 'mailing/home.html' %}
{% load static %}

{% block content %}

<div class="col-12 text-center">
    <h1>
        Доступ к странице заблокирован
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:home' %}">На главную</a>
</div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailing/home.html' %}
{% load user_tags %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<div class="row">
    <div class="col-2 mx-auto">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body mx-20">
                <form method="post" enctype="multipart/form-data"></form>
                <h5 class="card-title">{% if object.first_name != '' and object.last_name != '' %} {{object.first_name}} {{object.last_name}} {% else %} {{object.email}} {% endif %}</h5>
                <img src="{{object.avatar | media_filter }}">
                <p class="card-text">Дата регистрации: {{object.date_joined}}</p>
                <p class="card-text">Последний вход: {{object.last_login}}</p>
                <p class="card-text">Подтверждён: {{object.is_verified}}</p>
                <p class="card-text">Менеджер: {{object.is_staff}}</p>
                <p class="card-text">Администратор: {{object.is_superuser}}</p>
                <p class="card-text">Заблокирован: {{object.is_block}}</p>
                <a href="{% url 'users:manager_users' %}" class="btn btn-md btn-outline-primary mx-auto">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="POST" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Зарегестрироваться
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/home.html' %}
{% load static %}

{% block content %}

{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Рассылки</h1>
                <p class="lead text-body-secondary">Личный кабинет менеджера</p>
            </div>
        </div>
    </section>

    <h1 class="fw-light text-center mb-3">Просмотр пользователей</h1>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row    -cols-md-3 g-3">
                {% for object in objects_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{% if object.first_name != '' and object.last_name != '' %} {{object.first_name}} {{object.last_name}} {% else %} {{object.email}} {% endif %}</h1>
                            <p class="card-text">Дата регистрации: {{object.date_joined}}</p>
                            <p class="card-text">Последний вход: {{object.last_login}}</p>
                            <p class="card-text">Подтверждён: {{object.is_verified}}</p>
                            <p class="card-text">Менеджер: {{object.is_staff}}</p>
                            <p class="card-text">Администратор: {{object.is_superuser}}</p>
                            <p class="card-text">Заблокирован: {{object.is_block}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'users:manager_users_detail' object.pk%}" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                    {% if object.is_block %}
                                    <a href="{% url 'users:manager_users_block' object.pk %}" class="btn btn-sm btn-outline-success">Разблокировать</a>
                                    {% else %}
                                    <a href="{% url 'users:manager_users_block' object.pk %}" class="btn btn-sm btn-outline-danger" id="liveSUAlert">Заблокировать</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
</main>
{% endif %}
{% endblock %}